Enabled: true
Default MOTD: "&d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <"
Animation:
  Ticks: 2
  MOTDs:
  - "&d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "  &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "    &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "      &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "        &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "          &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "            &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "              &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                  &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                    &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                      &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                        &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                          &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                            &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                              &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                  &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                    &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                      &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                        &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                          &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                            &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                              &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                                &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                              &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                            &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                          &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                        &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                      &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                    &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                  &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                                &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                              &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                            &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                          &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                        &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                      &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                    &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                  &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "                &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "              &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "            &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "          &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "        &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "      &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "    &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "  &d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
  - "&d&lAnimated&5&lMOTD\n           &6> > >     &b&lPing&9&lAPI     &6< < <                          "
